// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKwd446u9WUs8E8NAy-PkRu0IC6E9Jloc',
    appId: '1:89378995044:web:6c86fff756c1f1fe34d871',
    messagingSenderId: '89378995044',
    projectId: 'etiss-a151f',
    authDomain: 'etiss-a151f.firebaseapp.com',
    storageBucket: 'etiss-a151f.firebasestorage.app',
    measurementId: 'G-4V08M4D8W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoKsXFAhFL28LvrGXhtd-MZqdS0KYr2U',
    appId: '1:89378995044:android:4a23e3eb8e97333134d871',
    messagingSenderId: '89378995044',
    projectId: 'etiss-a151f',
    storageBucket: 'etiss-a151f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7v3Lb2u70aFcmEoynbZTA4YcYLa7My00',
    appId: '1:89378995044:ios:aa1ae66133f4645a34d871',
    messagingSenderId: '89378995044',
    projectId: 'etiss-a151f',
    storageBucket: 'etiss-a151f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7v3Lb2u70aFcmEoynbZTA4YcYLa7My00',
    appId: '1:89378995044:ios:aa1ae66133f4645a34d871',
    messagingSenderId: '89378995044',
    projectId: 'etiss-a151f',
    storageBucket: 'etiss-a151f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}